imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

parameters:
    locale: ru

framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    translator:
        fallback: en
    fragments: ~
    http_method_override: true

twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

doctrine:
    dbal:
        driver: "%database_driver%"
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    port: "%mailer_port%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    encryption: tls
    auth_mode: login
    spool:
        type: automailer

tss_automailer:
    beanstalk: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Gram\UserBundle\Entity\User

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: '@GramUserBundle/Resources/config/serializer'
            GramUserBundle:
                namespace_prefix: "Gram\\UserBundle"
                path: '@GramUserBundle/Resources/config/serializer'

doctrine_migrations:
    dir_name: %kernel.root_dir%/migrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Migrations