app_index:
    path: /
    methods: [GET]
    defaults: {_controller: GramSurveyBundle:Survey:index}

app_info:
    path: /info
    methods: [GET]
    defaults: {_controller: GramSurveyBundle:Survey:info}

gram_survey:
    resource: @GramSurveyBundle/Resources/config/routing.yml
    prefix: /

gram_user:
    resource: @GramUserBundle/Resources/config/routing.yml
    prefix: /
