survey_bundle_spa_survey:
    resource: routing/survey.yml
    prefix:   /spa/v1

survey_bundle_spa_completed_survey:
    resource: routing/CompletedSurvey.yml
    prefix:   /spa/v1

survey_bundle_spa_survey_statistics:
    resource: routing/statistics.yml
    prefix:   /spa/v1