services:
    survey.rest_service:
         class: Gram\SurveyBundle\Services\SurveyService
         arguments: [@service_container]

    survey.completed_survey_rest_service:
         class: Gram\SurveyBundle\Services\CompletedSurveyService
         arguments: [@service_container]

    survey.service_export:
        class: Gram\SurveyBundle\Services\ExportService
        arguments: [@service_container]

    rest.rest_service:
        class: Gram\SurveyBundle\Services\RestService
        arguments: [@service_container]

    rest.form_errors_serializer:
        class: Gram\SurveyBundle\Services\FormErrorsSerializer
        arguments: [@service_container]

    survey.completed_survey_listener:
        class: Gram\SurveyBundle\Listener\CompletedSurveyListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: prePersist}